### ISSUE TITLE
显存占用会随时间增加逐渐耗尽

### ISSUE THREAD

**Issue by geographerwang** [Orillusion/orillusion-webgpu-samples#2]
cubesOffsets等几个立方体绘制显存占用会随时间增加耗尽后，会继续内存。
应该是webgpu调度问题吧，请教下我们自己能控制gpu显存释放么
![显存占用](https://user-images.githubusercontent.com/12079968/163307893-789fa734-b91e-4ad8-aae3-9f504ed08b8b.png)

**Comment by lslzl3000** [comment]
感谢发现问题，显存一直增加是因为在draw里每次都创建了一个新的texture，所以会不停的消耗显存，直到用完触发GPU强制GC。该Bug已经修复，pull最新的代码即可。

通常来讲，我们创建的GPUBuffer 和 GPUTexture 首先要避免在frame里循环创建，其次，如果确定使用完成，不需要再用了，可以通过 GPUBuffer.destroy() 和 GPUTexture.destroy() 进行销毁回收显存
