### ISSUE TITLE
Failed to convert value to 'GPUPipelineLayout'

### ISSUE THREAD

**Issue by zhoureal** [Orillusion/orillusion-webgpu-samples#3]
Failed to read the 'layout' property from 'GPUPipelineDescriptorBase': Failed to convert value to 'GPUPipelineLayout'

![image](https://user-images.githubusercontent.com/12002497/172134174-0d1d185e-f3ba-45db-b5cf-bee64d3bcf7c.png)

mac 
![image](https://user-images.githubusercontent.com/12002497/172134779-84f18c31-5588-4536-986e-9c25d175fdc3.png)

 
chrome 版本 102.0.5005.61（正式版本） (x86_64)

**Comment by lslzl3000** [comment]
From Chrome v103, the GPUPipelineLayout has a new default value 'auto', and the 'layout' cannot be leave blank in GPUPipelineDescriptor anymore. But layout: 'auto' is not supported before v103. So please try to upgrade your chrome to Canary channel or wait next release
