### ISSUE TITLE
示例中的一些问题

### ISSUE THREAD

**Issue by shenburen** [Orillusion/orillusion-webgpu-samples#4]
basic lights示例中，我注释掉点光源相关的代码时，并没有看到平行光所产生的的效果。

**Comment by lslzl3000** [comment]
能提供代码和截图吗，注释掉了哪些代码

**Comment by shenburen** [comment]
1、当平行光的强度拉满时，我们并分不清有没有产生平行光；
2、当平行光的强度减到最小时，我们也是无法分辨的；
3、把着色器中点光源影响的那一行注释掉；
4、可以看到图中，平行光强度虽然为最大，但是并看不出来有平行光的效果。
如果是我的操作当中产生了一些问题，请谅解一下，也十分感谢您百忙之中抽出时间回复我。










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Orillusion/orillusion-webgpu-samples"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月13日(星期三) 中午1:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Orillusion/orillusion-webgpu-samples] 示例中的一些问题 (Issue #4)





 
能提供代码和截图吗，注释掉了哪些代码

**Comment by shenburen** [comment]
<img width="1920" alt="1" src="https://user-images.githubusercontent.com/52999397/178656435-1b6c464c-73b7-452c-833e-98b8671aebad.png">
<img width="1920" alt="2" src="https://user-images.githubusercontent.com/52999397/178656476-50502666-6685-4f35-abe1-17fd5274e635.png">
<img width="508" alt="3" src="https://user-images.githubusercontent.com/52999397/178656501-e10a2f45-8bbe-42bc-8509-9bbad04d322a.png">
<img width="1920" alt="4" src="https://user-images.githubusercontent.com/52999397/178656516-709a751b-04e9-447c-88d7-f015c24b292f.png">

**Comment by lslzl3000** [comment]
已修复，少了一行更新灯光的代码，感谢发现问题
