### ISSUE TITLE
Example incompatible with Firefox Nightly

### ISSUE THREAD

**Issue by noahlam** [Orillusion/orillusion-webgpu-samples#6]
Cause error when running example in firefox nightly.

It output following error message: 

```
Uncaught (in promise) TypeError: GPUDevice.createRenderPipelineAsync: 'layout' member of GPUPipelineDescriptorBase is not an object.
    initPipeline basicTriangleMsaa.ts:57
    run basicTriangleMsaa.ts:87
```

FIrefox Nightly Version: 105.0a1 (2022-08-03) (64 位)
System: MacOS Monterey

**Comment by lslzl3000** [comment]
Firefox use [wgpu](https://wgpu.rs/) as webgpu backend.

Unlike Google Dawn, wgpu only use 'stable' webgpu standard for publish release. So Firefox won't support some of the new Webgpu APIs.  

As a webgpu demo repo, we try to use latest webgpu standard. So in current stage, we are targeting Chromium / Dawn based browsers only.

**Comment by noahlam** [comment]
Chromium has a bug that cannot get adapter when refreshing. It happened in MacBook Pro 2020 but not happened in MacBook Pro 2017.

My test code:
```
<script>
async function init() {
    const { gpu } = navigator;
    if (!gpu) throw new Error("WEB GPU Unsupported");

    const adapter = await gpu.requestAdapter();
    if (!adapter) throw new Error("Cannot get Adapter");
    console.log(adapter);
}

init();

</script>
```

Running result:
![Running result](https://user-images.githubusercontent.com/22094266/182988905-1a6cec90-644d-4402-b327-fdb659049669.gif)

**Comment by lslzl3000** [comment]
webgpu is not public yet, only work under specific domain with [origin-trail](https://developer.chrome.com/origintrials/#/view_trial/118219490218475521) token    
Or work with chrome://flags/#enable-unsafe-webgpu flag

**Comment by noahlam** [comment]
It isn't always got error. just when refreshing.

I had tried to use your trail token and running server with port 3000. It still happened.
